#!/usr/bin/env python3
"""
Customer Service Agent - Simple Console Chat with Memory
"""

import os
from dotenv import load_dotenv
load_dotenv()

from src.chains import CustomerServiceChain


def display_conversation_summary(summary):
    """Display the ConversationSummary object in a formatted way."""
    print("\n" + "="*60)
    print("📋 CONVERSATION SUMMARY GENERATED BY CHAIN")
    print("="*60)
    
    # Basic summary info
    print(f"🕒 Timestamp: {summary.timestamp}")
    print(f"👤 Customer ID: {summary.customer_id}")
    print(f"📝 Summary: {summary.conversation_summary}")
    print(f"🏷️ Category: {summary.query_category}")
    print(f"😊 Sentiment: {summary.customer_sentiment}")
    print(f"⚡ Urgency: {summary.urgency_level}")
    print(f"📦 Products: {', '.join(summary.mentioned_products) if summary.mentioned_products else 'None'}")
    print(f"✅ Resolution: {summary.resolution_status}")
    print(f"🔄 Follow-up required: {'Yes' if summary.follow_up_required else 'No'}")
    
    # Actions taken
    if summary.actions_taken:
        print(f"\n🔧 Actions Taken:")
        for i, action in enumerate(summary.actions_taken, 1):
            print(f"   {i}. {action}")
    
    # Extracted entities
    print(f"\n🔍 Extracted Information:")
    entities = summary.extracted_information
    if entities.product_name:
        print(f"   📱 Product: {entities.product_name}")
    if entities.order_number:
        print(f"   🎫 Order Number: {entities.order_number}")
    if entities.date:
        print(f"   📅 Date: {entities.date}")
    
    print("="*60)


def main():
    """Simple chat loop with conversation memory."""
    
    print("=" * 60)
    print("🤖 Customer Service Agent - Simple Chat")
    print("Type 'quit' to exit")
    print("=" * 60)
    
    # Initialize agent
    agent = CustomerServiceChain()
    
    # Simple conversation memory
    conversation_history = []
    
    # Simple chat loop
    while True:
        try:
            # Get user input
            user_input = input("\n💭 You: ").strip()
            
            # Check for exit
            if user_input.lower() in ['quit', 'exit', 'q']:
                print("\n👋 Goodbye!")
                break
            
            # Skip empty input
            if not user_input:
                continue
            
            # Add context to the query if we have history
            if conversation_history:
                context = f"Conversation so far: {' | '.join(conversation_history)}. Current question: {user_input}"
                full_query = context
            else:
                full_query = user_input
            
            # Process query
            print("🤖 Processing...")
            result = agent.process_query(full_query)
            
            # Show response
            if result:
                print(f"📋 Category: {result['metadata']['category']}")
                print(f"💬 {result['response']}")
                
                # Add to conversation memory (keep last 5 exchanges)
                conversation_history.append(f"User: {user_input}")
                conversation_history.append(f"Agent: {result['response'][:100]}...")
                
                # Keep only last 10 items (5 exchanges)
                if len(conversation_history) > 10:
                    conversation_history = conversation_history[-10:]
                    
            else:
                print("❌ Sorry, I couldn't process that. Please try again.")
                
        except KeyboardInterrupt:
            print("\n👋 Chat interrupted. Goodbye!")
            break
        except Exception as e:
            print(f"❌ Error: {e}")
    
    # Show final conversation summary if we have any results
    if conversation_history:
        print("\n\n🤖 Processing...")
        
        # Get the last result to show the summary
        if len(conversation_history) >= 2:
            last_user_msg = conversation_history[-2].replace("User: ", "")
            last_result = agent.process_query(last_user_msg)
            
            if last_result and last_result.get('summary'):
                display_conversation_summary(last_result['summary'])
            else:
                print("No conversation summary available.")
        else:
            print("No conversation history to summarize.")


if __name__ == "__main__":
    # Check API key
    if not os.getenv('OPENAI_API_KEY'):
        print("❌ Error: OPENAI_API_KEY not set in .env file")
        exit(1)
    
    main()